// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUmr32j6euZIH85b8XDzgG78dMhh077Is',
    appId: '1:492804550546:web:700dadf2158bc889861b4b',
    messagingSenderId: '492804550546',
    projectId: 'janken-b9205',
    authDomain: 'janken-b9205.firebaseapp.com',
    storageBucket: 'janken-b9205.appspot.com',
    measurementId: 'G-JTHX0R81ZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRPLcaDoQiPbZcWO1nlmit6c1zyAo-mVs',
    appId: '1:492804550546:android:e6dfea4d19462f92861b4b',
    messagingSenderId: '492804550546',
    projectId: 'janken-b9205',
    storageBucket: 'janken-b9205.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVqzUGYJgQJauegrQTq7TwzFCR7dbeWjU',
    appId: '1:492804550546:ios:4150a3341c8b459a861b4b',
    messagingSenderId: '492804550546',
    projectId: 'janken-b9205',
    storageBucket: 'janken-b9205.appspot.com',
    iosBundleId: 'com.example.jankenGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVqzUGYJgQJauegrQTq7TwzFCR7dbeWjU',
    appId: '1:492804550546:ios:5bcb4e0b00018a46861b4b',
    messagingSenderId: '492804550546',
    projectId: 'janken-b9205',
    storageBucket: 'janken-b9205.appspot.com',
    iosBundleId: 'com.example.jankenGame.RunnerTests',
  );
}
